### ISSUE TITLE
Add text on final page

### ISSUE THREAD

**Issue by SiriPRIO** [prio-data/conflictcartographer#19]
På siste siden hvor det står at de kan lukke broweser vinduet. Kan vi legge in en setning om at vi tar kontakt med de for å prediketer neste tre månders periode 1.juli til 30. september i begynnelsen av juni

**Comment by Peder2911** [comment]
God idè! Skal legge det inn idag. ;)I

**Comment by Peder2911** [comment]
Fixed by 20366e5
