### ISSUE TITLE
Identity of user

### ISSUE THREAD

**Issue by indigocodeit** [prio-data/conflictcartographer#27]
Make it visible who is logged in, option to log out. Extra: possibly could also see countries assigned on a user page? Including if there are multiple rounds of prediction/could see old predictions there, see how right you were previously.

**Comment by Peder2911** [comment]
Hey! This is a good suggestion, although the "Extra" section definitely warrants its own issue, since it's a lot more to handle.
The profile-page showing assigned ctries / results is definitely something we want to do long-term, but I won't get around to it until end of March.

**Comment by Peder2911** [comment]
Added identification and logout button in 6a8994d
