### ISSUE TITLE
color accesibility

### ISSUE THREAD

**Issue by indigocodeit** [prio-data/conflictcartographer#32]
are the colors contrasting enough? can check with a site like this https://webaim.org/resources/contrastchecker/

**Comment by Peder2911** [comment]
Thanks for the tip! Will change if they aren't.

**Comment by Peder2911** [comment]
Thanks for the tip! Will change if they aren't.

**Comment by Peder2911** [comment]
Thanks for the tip! Will change if they aren't.

**Comment by Peder2911** [comment]
Main constrast color checked and found to be acceptable using the resource you linked to
