### ISSUE TITLE
Let users be able to delete their profile

### ISSUE THREAD

**Issue by kvelleby** [prio-data/conflictcartographer#44]
Users should be able to delete their profile/remove their consent for us keeping their personal data. When a user deletes its profile, personal information must be deleted (e-mail address and institutional affiliation). Profession (if provided) should be kept. I do not know what the easiest technical implementation of this could be (perhaps replace email and affiliation with empty string and add a flag for whether or not the profile has been deleted?).

If this profile_deletion method could also be made available for admin, that would be nice (since some users might prefer sending an email about removing their consent instead of logging on themselves. In that case, it should be easy for us to do.

The user should be notified that deleting the profile is permanent and that they will not be able to log onto or use Conflict Cartographer again without registering a new user.

**Comment by kvelleby** [comment]
Note: Making the profile_deletion method available to admin is not important, but a feature that would be nice to have in the future.

**Comment by Peder2911** [comment]
This is now added via https://github.com/prio-data/conflictcartographer/commit/a9568c15811da897a71a564ba39d1ab4287d35fa.

Closing!
