### ISSUE TITLE
Emailing Functionality

### ISSUE THREAD

**Issue by amobe1** [prio-data/conflictcartographer#48]
Emails/Lists
It would be great to have different email templates (I have these drafted) and associated lists that I could add/remove people from as the individual progresses through the stages of the project. 
* Initial invitation email/list 
* Email notifying the new prediction quarter has opened (for people who didn't participate in the most recent quarter but who have participated in the past)
* Email thanking people for predicting, notifying them of new prediction period (for people who did participate in most recent quarter)
* Email notifying participant that their results are available 

Other
* It would be great to have a link at the bottom of the email templates where people can choose to unsubscribe from future emails. A few people have emailed asking not to be emailed again.

**Comment by Peder2911** [comment]
Cool! Thank you for these. We might want to think about how "obnoxious" we want to be, maybe even allowing users to specify which reminders they want to receive... I'll think about this.

**Comment by amobe1** [comment]
Hmm, yeah. I've tried to keep it to no more than 2 emails per quarter, plus one for respondents notifying them that their results are ready.
